version: "3.9"

services:
    app:
        container_name: e-ama-maintenance
        image: e-ama-maintenance
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:80"
